services:
    app:
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        container_name: '$COMPOSE_PROJECT_NAME-app'
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - internal

    mysql:
        image: 'mysql:8'
        container_name: '$COMPOSE_PROJECT_NAME-mysql'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_NAME}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - internal

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        container_name: '$COMPOSE_PROJECT_NAME-phpmyadmin'
        ports:
            - '8080:80'
        environment:
            PMA_HOST: '${DB_HOST}'
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
            UPLOAD_LIMIT: 64M
        networks:
            - internal
        depends_on:
            - mysql
networks:
    internal:
        driver: bridge

volumes:
    mysql:
        driver: local
